# numpy: Introduction

Let's import the `numpy` module.

In [1]:
#clear
import numpy as np

In [3]:
n = 10  # CHANGE ME
a1 = list(range(n))
a2 = np.arange(n)

if n <= 10:
    print(a1)
    print(a2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
%timeit [i**2 for i in a1]

100000 loops, best of 3: 2.36 µs per loop


In [5]:
%timeit a2**2

1000000 loops, best of 3: 1.06 µs per loop


Numpy Arrays: much less flexible, but:

* much faster
* less memory

---

Ways to create a numpy array:

* Casting from a list

In [6]:
#clear
np.array([1,2,3])

array([1, 2, 3])

* `linspace`

In [7]:
#clear
np.linspace(-1, 1, 10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

* `zeros`

In [8]:
#clear
np.zeros((10,10), np.float64)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

---

Operations on arrays propagate to all elements:

In [9]:

a = np.array([1.2, 3, 4])
b = np.array([0.5, 0, 1])

Addition, multiplication, power, .. are all elementwise:

In [10]:
#clear
a+b

array([ 1.7,  3. ,  5. ])

In [11]:
#clear
a*b

array([ 0.6,  0. ,  4. ])

In [12]:
#clear
a**b

array([ 1.09544512,  1.        ,  4.        ])

Matrix multiplication is `np.dot(A, B)` for two 2D arrays.

---

Numpy arrays have two (most) important attributes:

In [13]:
a = np.random.rand(5, 4, 3)
a.shape

(5, 4, 3)

The `.shape` attribute contains the dimensionality array as a tuple. So the tuple `(5,4,3)` means that we're dealing with a three-dimensional array of size $5 \times 4 \times 3$.

(`numpy.random.rand` just generates an array of random numbers of the given shape.)

In [14]:
a.dtype

dtype('float64')

Other `dtype`s include `np.complex64`, `np.int32`, ...